
test_dns:
#	GOCACHE=off go test -v github.com/HikoQiu/go-eureka-client/eureka -run=Test_TxtResolve
	GOCACHE=off go test -v github.com/HikoQiu/go-eureka-client/eureka -run=Test_GetServiceUrls
test:
	GOCACHE=off go test -v github.com/HikoQiu/go-eureka-client/eureka -run=Test_$(func)

